apiVersion: v1
kind: LimitRange
metadata:
  name: mem-min-max
spec:
  limits:
  - max: # 上限
      memory: 200Mi
      cpu: 2
    min: # 下限
      memory: 100Mi
      cpu: 0.1
    defaultRequest: # デフォルト
      memory: 100Mi
      cpu: 0.5
    type: Container # 適用するタイプ
