apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc
spec:
  securityContext:        # コンテナの実行プロセスのID
    runAsUser: 65534      #    ユーザーID   ポッド実行時UID
    runAsGroup: 65534     #    グループID   ポッド実行時GID
    fsGroup: 65534        #    補足グループ  ファイル作成時のグループを指定
  containers:
    - name: my-web-service
      image: ghcr.io/takara9/ex1:1.0   # コンテナイメージ
      volumeMounts:
      - name: pv-data      # ボリューム名
        mountPath: /mnt    #    マウント位置（パス）
  volumes:
    - name: pv-data           # ボリューム名
      persistentVolumeClaim:  #    PVCを選択
        claimName: my-vol     #    PVCの名前
