
apiVersion: v1
kind: Pod
metadata:
  name: my-ubuntu2
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    args:
      - /bin/sh
      - -c
      - tail -f /dev/null
    envFrom:
      - configMapRef:
          name: db-conf
