apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
items:
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    name: default
    namespace: argocd
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    destinations:
    - namespace: '*'
      server: '*'
    sourceRepos:
    - '*'
    sourceNamespaces:
    - app-team-one
    - app-team-two
