apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  containers:
    - image: ghcr.io/takara9/sec-nginx:1.0
      name: nginx
      ports:
        - containerPort: 80
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
        seccompProfile: 
          type: RuntimeDefault
        runAsUser: 101
        runAsGroup: 101
