version: '3.1'

networks:
  my-word-net:
    driver: bridge

volumes:
  wordpress:
    driver: local
  db:
    driver: local

services:
  my-wordpress:
    image: wordpress
    restart: always
    ports:
      - 8200:80
    environment:
      WORDPRESS_DB_HOST: my-mysql
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wp
    volumes:
      - wordpress:/var/www/html
    networks:
      - my-word-net

  my-mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-word-net
