kind: Pod
apiVersion: v1
metadata:
  name: my-pod-mc
spec:
  containers:
   - name: my-container-1  # メインコンテナと呼ばれる事もある
     image: ghcr.io/takara9/ex1:1.0
     ports:
      - name: ex1-port
        containerPort: 9100
   - name: my-container-2  # サポートコンテナやサイドカーコンテナと呼ばれる事がある
     image: ghcr.io/takara9/ex3:1.0
     ports:
      - name: ex3-port
        containerPort: 3000

