apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pods
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: my-pod
  template: 
    metadata:     
      labels:
        app: my-pod
    spec:
      nodeName: minikube-m03  # ノードネーム
      containers:
        - name: ubuntu
          image: ghcr.io/takara9/ex1:1.0
          command: ["tail", "-f", "/dev/null"] 
  