---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-and-passwd
  namespace: prod
spec:
  encryptedData:
    passwd: AgCG+71+tPds5qh9/QwuQbJJv+CX+7oj9GO08C53eE0lYgsEHAQ6xWpzPjAyvh3HcC7WNOxh3mg4xrK1BCdiaa0WZc+6frhcoNdeaFkM5SvSlHMGOxTboWgoRI5XVedviU4L/hjdRDZ3FnE46gIqL1ToW8FPrIQ53r/8bnDlU1r2pW4IrzD6OrV8Na4675okZOFK3E+DCsLfSEFhpSQlQGGr0OaiQEi42MBIqd+gg8ZS6Nq8b/i1gpncYdmKc0oXVeAAHF0cVK+9htW3dsWii3tBf9Wt/SJTViRccmgN7kxoht6pt8UYOUSwtaKdef1N96R2h6rc4lNWErtqnOIu2kFNsXsXbhUkCwDMGglJwA7jHJYDGh1zh2ywbyqUAU0Dz1pg9UJZuNZlYe8O55R/M1Zqw4eB9+9Y1mHR4YwdZIb9Lgizk75D1WNVDjSZJIi9y7ghR6qXFob3d72/aprEBhcHpYZgOZsRcy6aCBSOO2PavtaATUXu/qeZa8M69to0nGjw//Y8QEh/pX03TNWBXRzCI7P3tCTDzazKR0H0CknWDq6lzJApnyyrPQzVAhxwVG7+eRKQqApqMMmz0a5dp206dqdLgOTQo3xtp60NOb+6jb71Sepfhly9wDJ5nWMTzFan2o+uzD22LxhT6P+hP0m9y7styX4dTLXpqmcdcksonkvXWUI4lpcUmH5/2W7jXf1eQguTY4wUX60=
    user-id: AgAEYIzmIMxAg3xqbsbZK5dBsiyfzDjk0z6/7KJ/vDvblLsTlKB3h9H9yofopYibMaeknyP7n6G9nteoz0wDXnXukUB6xmubF4NTkymlwMXSi5HQPjuqwoyMngFrqlotOs5uP8BFr5vq5IOY/YUPKe9UYyrJLzmwWPLjs5P0YOrjDO+n70qvpmQ8AACf7EiMNgMXfmZaysAcrOlsfqkVclF9dyhFpni7+/UmGqtO1PGx2LOB4Gys8/doDO2lBJ8wqZblqF/XyYR7EAujWyfuq1uhNWQDVpBH5xjsGC3fsM9Z0WrjocpX5J8OacVVd4CTD+QE3nYJY1GTtgxYsrgGXfHjgFFNEjr0nr6ffYnwcsCKkU26aJSet0i9c6H5xGtF3pstzI3bMWPJdB/YUTSprVugdrJpeJt3QbKZ7jNijfmTqxVFxoQroDHhR0o1GCWalo/alqQMmvB9FZKr3ZIKRkqWw8gN/NqozY6J1PV8HavR+kpI3pWdKnCtjQxdQfQPFaTK7m0B0S/0erZB4xaifFMVnH+IqKjiJTqiKnmRKf/nuuCdAT7YXLBiwUJRBvd2iYcXMfyJCFF5+/UC8uv6z5xchNp2PG+gvHypHFN08sa+YpE/Q+iKWjUmiENXRQa7jy1yl+/eCNmoaV/tssNrTTpE37c0AmHXj82EOLKGLLf1ISlzYRmNMJQeS/zXa7WvoVeNRawXQiaG
  template:
    metadata:
      creationTimestamp: null
      name: user-and-passwd
      namespace: prod
