apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
type: Opaque
stringData:
  aws_s3_url: http://minio.storage.svc.cluster.local:9000/
  aws_access_key_id: 8mToF3W8xhRUofPO5ag4
  aws_secret_access_key: QMc0Ked1FSJxUCTIo9tjsm0JzNMwSIkkauS3yQK8
