apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../bases
namespace: prod
patches:
- path: deployment_patches.yaml
- path: statefulsets_patches.yaml
- path: configmap-env.yaml
- path: secret.yaml
