apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
spec:
  securityContext:
    runAsNonRoot: true
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: my-container
    image: ghcr.io/takara9/my-ubuntu:0.3
    command: [ "bash", "-c", "tail -f /dev/null" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /mnt
