apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc2          # ポッド名
spec:
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
  containers:
    - name: ubuntu
      image: ghcr.io/takara9/ex1:1.0
      volumeMounts:
      - name: pv-data
        mountPath: /mnt
  volumes:
    - name: pv-data                    # ポッド内でのボリューム名
      persistentVolumeClaim:  
        claimName: my-vol-snapshot     # リストアして作成した永続ボリューム名