# MariaDBのサービス
apiVersion: v1
kind: Service
metadata:
  name: rest-service
spec:
  ports:
  - port: 9100
    name: webservice
  selector:
    app: rest-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
spec:          # (1)コントローラーのスペック
  replicas: 3  # (2)ポッドの要求数 
  selector:    # (3)対象ポッドを選択するためのセレクター (必須)
    matchLabels:
      app: rest-pod
  template:      # (4)ポッドのテンプレート 
    metadata:     
      labels:    # (5)コントローラが識別するためのラベル（必須)
        app: rest-pod
    spec:              # (6)ポッドのスペック
      securityContext: # (7)実行時のユーザーとグループ（任意)
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
      - name: ex1-rest
        image: ghcr.io/takara9/ex1
        imagePullPolicy: Always
        env:
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef: 
              name: env-var
              key: database_name
        - name: MARIADB_HOST
          valueFrom:
            configMapKeyRef: 
              name: env-var
              key: mariadb-host
        - name: MARIADB_READONLY_HOST
          valueFrom:
            configMapKeyRef: 
              name: env-var
              key: mariadb-readonly-host
        - name: MARIADB_PORT
          valueFrom:
            configMapKeyRef: 
              name: env-var
              key: mariadb-port
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef: 
              name: mariadb-secret
              key: mariadb-user
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: mariadb-secret
              key: mariadb-root-password
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: mariadb-secret
              key: mariadb-user-password
        ports:
        - name: service-port
          containerPort: 9100
        livenessProbe:   # /healthzをHTTPでGETして、STATUS=200であれば生存
          httpGet:
            path: /healthz
            port: service-port
          periodSeconds: 5
        readinessProbe:  # /readinessをHTTPでGETして、STATUS=200であれば準備完了
          httpGet:
            path: /readiness
            port: service-port
          periodSeconds: 5
     


