apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - image: registry.k8s.io/pause  # 何もしないコンテナ
    name: container1
    resources:
      #requests:
      #  memory: 1Mi
      #  cpu: 0.1
      limits:
        memory: 300Mi
        cpu: 0.5