apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-app-1
spec:
  type: NodePort
  selector:
    run: my-pod 
  ports:
  - name: my-service
    protocol: TCP
    port: 9100
    targetPort: 9100
