apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- secret.yaml
  - configmap-env.yaml
  - statefulsets-mariadb-cluster.yaml
  - job-create-tables.yaml
  - deployment-rest-service.yaml
  #- secret-backup.yaml
  #- job-backup-daily.yaml
images:
  - name: ghcr.io/takara9/ex1
    newName: ghcr.io/takara9/ex1
    newTag: "1.6"
  - name: mariadb
    newName: mariadb
    newTag: 11.3.2-jammy
