apiVersion: v1
kind: Pod
metadata:
  name: my-ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    args:
      - /bin/sh
      - -c
      - tail -f /dev/null
    volumeMounts:
    - name: configmap
      mountPath: /mnt
  volumes:
    - name: configmap
      configMap:
        name: app-conf
