apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  volumes:
    - name: secret-volume          # コンテナにマウントするための名前
      secret:  # シークレットを選択する設定（ここが違う点）
        secretName: dotfile-secret # シークレットの名前
  containers:
    - name: container-secret
      image: ghcr.io/takara9/ex1:1.0
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"  # このディレクトリの下にファイルが出来る