apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sc
  namespace: myns
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    runAsNonRoot: true
    seccompProfile: 
      type: RuntimeDefault
  volumes:
  - name: vol
    emptyDir: {}
  containers:
  - name: general
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
