apiVersion: batch/v1
kind: Job
metadata:
  name: create-tables
spec:
  template:
    spec:
      containers:
      - name: create-table
        image: mariadb:11.3.2-jammy
        imagePullPolicy: Always
        env:
        - name: MARIADB_DATABASE
          value: mydb
        - name: MARIADB_USER
          value: user1
        - name: MARIADB_HOST
          value: db-0.db.prod.svc.cluster.local
        - name: MARIADB_PORT
          value: '3306'
        - name: MARIADB_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-user-password
        command:
        - bash
        - "-c"
        - |
          set -ex
          mariadb --host $MARIADB_HOST --port $MARIADB_PORT --user $MARIADB_USER --password=$MARIADB_USER_PASSWORD $MARIADB_DATABASE <<EOF
          CREATE TABLE Persons (
            id INT NOT NULL AUTO_INCREMENT,
            first_name VARCHAR(50) NOT NULL,
            last_name VARCHAR(50),
            PRIMARY KEY (id),
            UNIQUE INDEX id_UNIQUE (id ASC)
          );
          INSERT INTO Persons VALUES (1, "sazae","fuguta");
          INSERT INTO Persons VALUES (2, "masuo","fuguta");
          INSERT INTO Persons VALUES (3, "namihei","isono");
          SELECT * from Persons;
          EOF
      restartPolicy: Never
  backoffLimit: 3
