apiVersion: v1
kind: Secret  # シークレット
metadata:
  name: my-secret
stringData:
  my-token: "5emitj"  # キーと値
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-secret
spec:
  containers:
    - name: m-container
      image: ghcr.io/takara9/ex1:1.0
      env: # 環境変数設定API
      - name: MY_PASSWORD # セットする環境変数名
        valueFrom:
          secretKeyRef:   # シークレットから取得
            name: my-secret  # シークレット名
            key: my-token    # 値を取得するキー
