apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apl-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: rest-apl
spec:
  project: default
  source:
    # repoURLの値は、フォークしたリポジトリに置き換えてください 
    repoURL: https://github.com/takara9/docker_and_k8s.git
    targetRevision: HEAD
    path: 4-11_CICD/2_Contiious_Distribution/webservice-system/overlays/stage

  destination:
    server: https://kubernetes.default.svc
    namespace: stage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true