name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - name: Checkout from github.com:takara9/docker_and_k8s.git
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Update submodules
      id: update
      run: git submodule update --remote --merge    
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        ls -al
        docker build -f ./3-5_App_development/3-5-5-java/Dockerfile.maven -t ghcr.io/takara9/ex5:dev ./3-5_App_development/3-5-5-java/
        docker images
    - name: Check vulnerabilities 
      run: |
        docker run -v /var/run/docker.sock:/var/run/docker.sock --rm aquasec/trivy image --no-progress ghcr.io/takara9/ex5:dev
    - name: Deploy to minikube
      run: |
        kubectl apply -f ./4-11_CICD/1_Continous_Integration/ci-deployment.yaml
        echo "--- waiting to running ---"
        sleep 60
        kubectl get svc -n exercise
        kubectl get deployment -n exercise
        kubectl get pod -n exercise
        kubectl describe pod -n exercise
    - name: Test service URLs
      run: |        
        minikube service -n exercise list
        minikube service -n exercise --url ex-5
        curl $(minikube service -n exercise ex-5 --url)/ping
