apiVersion: v1
kind: Service
metadata:
  name: rest-service
  namespace: prod
spec:
  ports:
  - port: 9100
    #name: webservice
  selector:
    app: my-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pods
  namespace: prod
spec:          # (1)コントローラーのスペック
  replicas: 3  # (2)ポッドの要求数 
  selector:    # (3)対象ポッドを選択するためのセレクター (必須)
    matchLabels:
      app: my-pod
  template:      # (4)ポッドのテンプレート 
    metadata:     
      labels:    # (5)コントローラが識別するためのラベル（必須)
        app: my-pod
    spec:              # (6)ポッドのスペック
      securityContext: # (7)実行時のユーザーとグループ（任意)
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
      - name: ex1-pod
        image: ghcr.io/takara9/ex1:1.5
        ports:
        - containerPort: 9100
      - name: my-pod
        image: ghcr.io/takara9/my-ubuntu:0.3
