apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-vol-snapshot
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: my-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi