apiVersion: v1
kind: Pod
metadata:
  name: my-pod-4
spec:
  securityContext:
    runAsNonRoot: true  # 非rootで実行する宣言
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: my-container
    image: ubuntu:latest
    command: [ "bash", "-c", "tail -f /dev/null" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /mnt
