apiVersion: v1
kind: Pod
metadata:
  name: my-pod-3
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: my-container
    image: ubuntu:latest
    command: [ "bash", "-c", "tail -f /dev/null" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /mnt
