apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-probe
spec:
  containers:
  - name: readiness
    image: ubuntu:latest
    args:
    - /bin/sh
    - -c
    - sleep 30; touch /tmp/healthy; tail -f /dev/null
    readinessProbe:
      exec:
        command: ["cat","/tmp/healthy"]
      initialDelaySeconds: 5
      periodSeconds: 5