apiVersion: v1
kind: Pod
metadata:
  name: pod-env
spec:
  containers:
  - name: my-container
    image: ghcr.io/takara9/ex1:1.0
    env: # 環境変数API
    - name: DEMO_GREETING  # 環境変数名
      value: "Hello from the environment" # 環境変数の値
