apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret-encrypted.yaml
  - ../../bases
namespace: stage
patches:
- path: deployment_patches.yaml
- path: statefulsets_patches.yaml
- path: configmap-env.yaml
#- path: secret.yaml