apiVersion: v1
kind: ConfigMap
metadata:
  name: game-params
data:
  # ファイルスタイル　キーとバリュー
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true   
