apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-kv
spec:
  containers:
    - name: ex1-container 
      image: ghcr.io/takara9/ex1:1.0        # 3-5-1で作ったコンテナイメージ
      command: ["tail", "-f", "/dev/null"]  # コンテナを待機状態にする
      volumeMounts:
      - name: params
        mountPath: "/config" # マウントポイント
        readOnly: true
  volumes:
  - name: params
    configMap:    # コンフィグマップをボリュームとして利用
      name: game-params # コンフィグマップ名