apiVersion: v1
kind: Pod
metadata:
  name: probes
spec:
  containers:
  - name: probes
    ports:
    - name: probe-port
      containerPort: 9100
      hostPort: 9100

    image: ghcr.io/takara9/probe:1.0
    livenessProbe:
      httpGet:
        path: /healthz
        port: probe-port
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /readiness
        port: probe-port
      initialDelaySeconds: 5
      periodSeconds: 5
