apiVersion: v1
kind: LimitRange
metadata:
  name: mem-min-max
spec:
  limits:
  - max:
      memory: 1Gi
      cpu: 1
    min:
      memory: 1Mi
      cpu: 0.1
    defaultRequest:
      memory: 256Mi
      cpu: 0.1
    type: Container
