apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pods
spec:
  replicas: 3
  selector:            # デプロイメント（コントローラー）とポッドの対応付けに必須
    matchLabels:
      app: my-pod
  template:            # ポッドテンプレート
    metadata:     
      labels:          # デプロイメント（コントローラー）とポッドの対応付けに必須
        app: my-pod
    spec:
      containers:
      - name: webservice
        image: ghcr.io/takara9/ex1:1.5
        ports:
        - containerPort: 9100
