apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  replicas: 2
  volumeClaimTemplates:
  - metadata:
      name: data-vol
    spec:
      storageClassName: "csi-hostpath-sc"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Mi