apiVersion: v1
kind: Pod
metadata:
  name: pod-std
  namespace: myns
spec:
  volumes:
  - name: vol
    emptyDir: {}
  containers:
  - name: general
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: vol
      mountPath: /data/demo
