apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pods
spec:
  replicas: 3 
  selector: 
    matchLabels:
      app: my-pod
  template: 
    metadata:     
      labels:   # ラベルは、コントローラとサービスの識別に使用
        app: my-pod
    spec:
      containers:
      - name: ex1-pod
        image: ghcr.io/takara9/ex1:1.5
        ports:
        - containerPort: 9100
