## サービスのマニフェスト例
apiVersion: v1
kind: Service
metadata:
  name: ex1       # サービス名
spec:
  type: ClusterIP # ClusterIPはデフォルトで省略可能
  ports:
  - port: 80
    targetPort: 9100
  selector:       # セレクターでリクエストの転送先ポッドを決定
    apg: my-grp1  # この2つのラベルと一致するポッドへ転送
    app: my-pod

