apiVersion: v1
kind: Pod
metadata:
  name: apparmorprofile1
spec:
  securityContext:
    appArmorProfile:
      type: RuntimeDefault
  containers:
  - image: registry.k8s.io/pause
    name: container1
  initContainers:
  - image: registry.k8s.io/pause
    name: initcontainer1
