apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-probe
spec:
  containers:
  - name: liveness
    image: ubuntu:latest
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; tail -f /dev/null
    livenessProbe:
      exec:
        command: ["cat", "/tmp/healthy"]
      initialDelaySeconds: 5
      periodSeconds: 5