apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-sc
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc
spec:
  restartPolicy: OnFailure
  containers:
    - name: ubuntu
      image: ghcr.io/takara9/my-ubuntu:0.2
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
      - name: data
        mountPath: /mnt
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc-hostpath