apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pods
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: my-pod
  template: 
    metadata:     
      labels:
        app: my-pod
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: ubuntu
          image: ghcr.io/takara9/ex1:1.0
