apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["tail", "-f","/dev/null"]
      env:
        # 環境変数の定義
        - name: PLAYER_INITIAL_LIVES # 環境変数名
          valueFrom:
            configMapKeyRef:
              name: game-demo           # コンフィグマップ名
              key: player_initial_lives # 値を取得するキー
        - name: UI_PROPERTIES_FILE_NAME
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: ui_properties_file_name
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes: # コンフィグマップをファイルとしてマウントパス以下に配置する
  - name: config
    configMap:
      name: game-demo
      items:
      - key: "game.properties"
        path: "game.properties"
      - key: "user-interface.properties"
        path: "user-interface.properties"
