apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # nameは、以下のspecのフィールドの<plural>.<group>と一致しなければならない
  name: crontabs.stable.example.com
spec:
  group: stable.example.com # REST-APIのパス /apis/<group>/<version>　
  versions:          # 複数バージョンを記述できる
    - name: v1
      served: true   # REST API経由で提供することを有効/無効にするフラグ
      storage: true  # カスタム リソースをストレージに永続化する
      schema:        # スキーマを記述
        openAPIV3Schema:  # OpenAPI v3 を検証とプルーニングに使用 
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                  pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
                image:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10                
  scope: Namespaced
  names:
    plural: crontabs  # 複数形名は、REST-APIのパスに使用 /apis/<group>/<version>/<plural>
    singular: crontab # 単数系名は、CLIと表示用の別名として使用
    kind: CronTab     # kind は CamelCase の単数形です。リソース マニフェストではこれを使用します。
    shortNames:       # フルネームに代わるショートネーム
    - ct
